:sparkles: #24 feat: object storage 연결 임시 코드
judy5050/InearProject pull request #25
Opened 2022-10-06 17:01 UTC by judy5050

2022-10-28 14:47 UTC, jsungmin6 requested changes

2022-10-28 14:47 UTC, jsungmin6 commented on inear/src/main/java/com/inear/model/PostAlarmReq.java
> +    private String name;
1. term repeat -> 타미랑 얘기해서 제거 해야할 ㄷ스?
2. message는 List로 받기로 한거야?
3. LocalTime 보단 LocalDateTime이 날듯

2022-10-28 14:47 UTC, jsungmin6 commented on inear/src/main/java/com/inear/inear/controller/AlarmController.java
> +    }
파라미터 밸리데이션은 나중에 @Vaild 기능 등으로 제거하는게 좋을 듯

2022-10-28 14:47 UTC, jsungmin6 commented on inear/src/main/java/com/inear/inear/controller/AlarmController.java
> +        jwtService.getUserId();
PathVariable 로 받는 id 값과 jwt의 id가 같은지 검증하는 로직 필요할 듯

2022-11-06 10:04 UTC, judy5050 commented on inear/src/main/java/com/inear/inear/controller/AlarmController.java
> +    }
오호~~ 좋은 의견 👍

2022-11-06 10:05 UTC, judy5050 commented on inear/src/main/java/com/inear/model/PostAlarmReq.java
> +    private String name;
LocalDateTime 으로 하면 어차피 날짜는 사용하지 않아서 굳이? LocalDateTime 으로 써야하나 싶은데 왜 LocalDateTime 이 더 낫다고 하는거야?

2022-11-06 10:05 UTC, judy5050 commented on inear/src/main/java/com/inear/model/PostAlarmReq.java
> +    private String name;
term 은 저거 의논하기 전에 한거라.. 맞아.. 없애야 할덧.. 
message는 물건별로 List로 받기로 회의할때 의논했었어 !

2022-11-06 14:01 UTC, jsungmin6 commented on inear/src/main/java/com/inear/model/PostAlarmReq.java
> +    private String name;
음 그러네 알람시간이면 LocalTime 이 더 맞겠다ㅎㅎ 무시해줭

2022-11-12 10:45 UTC, merged